config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users
  resources :plays do
    resources :reviews
  end

  root 'plays#index'

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :categories

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/play.rb
class Play < ActiveRecord::Base

  belongs_to :user
  belongs_to :category
  has_many :reviews

  validates :title, presence: true
  validates :description, presence: true
  validates :director, presence: true

  has_attached_file :play_img, styles: { play_index: "250x350>", play_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :play_img, content_type: /\Aimage\/.*\Z/
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ActiveRecord::Base

  belongs_to :user
  belongs_to :play

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :plays
  has_many :reviews

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :find_play, only: [:show, :edit, :update, :destroy]
  before_action :list_categories, only: [:new, :edit]
  before_action :authenticate_user!, only: [:new, :edit]

  def index
    if params[:category].blank?
      @plays = Play.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @plays = Play.where(category_id: @category_id).order("created_at DESC")
    end
  end

  def show
    if @play.reviews.blank?
      @average_review = 0
    else
      @average_review = @play.reviews.average(:rating).round(2)
    end
  end

  def new
    @play = current_user.plays.build
  end

  def create
    @play = current_user.plays.build(play_params)
    @play.category_id = params[:category_id]

    if @play.save
      redirect_to @play
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @play.category_id = params[:category_id]

    if @play.update(play_params)
      redirect_to @play
    else
      render 'edit'
    end
  end

  def destroy
    @play.destroy
    redirect_to root_path
  end

  private

  def find_play
    @play = Play.find(params[:id])
  end

  def play_params
    params.require(:play).permit(:title, :description, :director, :category_id, :play_img)
  end

  def list_categories
    @categories = Category.all.map{ |c| [c.name, c.id ]}
  end

end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play
  before_action :find_review, except: [:new, :create]
  before_action :authenticate_user!, only: [:new, :edit]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.play_id = @play.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to play_path(@play)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to play_path(@play)
    else
      render 'edit'
    end
  end

  def destroy
    @review.destroy

    redirect_to play_path(@play)
  end

  private

  def find_play
    @play = Play.find(params[:play_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_review
    @review = @play.reviews.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_main.html.erb
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Broadway", root_path, class: "navbar-brand" %>
    </div>

    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <% Category.all.each do |category| %>
          <li class="<% 'active' if params[:category] == category.name %>">
            <%= link_to category.name, plays_path(category: category.name), class: "link" %>
          </li>
          <% end %>
        </ul>
      </li>
      <% if user_signed_in? %>
      <li><%= link_to "Add Play", new_play_path %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav pull-right">
      <% if user_signed_in? %>
      <li class="navbar-text">Signed in as <%= current_user.email %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
      <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Broadway</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid">
    <%= render 'layouts/nav' %>
    <%= render 'layouts/main' %> 
  </div>
</body>
</html>

app/views/plays/_form.html.erb
<%= form_for @play do |f| %>

<div class="form-group">
  <label for="inputLabel">Image Input</label>
  <%= f.file_field :play_img %>
</div>

<div class="form-group">
  <%= select_tag(:category_id, options_for_select(@categories), prompt: "Select Category", class: "form-control") %>
</div>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", rows: "5" %>
</div>

<div class="form-group">
  <%= f.label :director %>
  <%= f.text_field :director, class: "form-control", placeholder: "Director" %>
</div>

<div>
  <%= f.submit "Create", class: "btn btn-primary" %>
</div>

<% end %>

app/views/plays/edit.html.erb
<h1>Edit <%= @play.title %></h1>

<%= form_for @play do |f| %>

<div class="form-group">
  <label for="inputLabel">Image Input</label>
  <%= f.file_field :play_img %>
</div>

<div class="form-group">
  <%= f.select(:category_id, @categories, html_options: { class: "form-control" }) %>
</div>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
</div>

<div class="form_group">
  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control", rows: "5" %>
</div>

<div class="form-group">
  <%= f.label :director %>
  <%= f.text_field :director, class: "form-control", placeholder: "Director" %>
</div>

<div>
  <%= f.submit "Save", class: "btn btn-primary" %>
</div>

<% end %>

app/views/plays/index.html.erb
<h1 id="current-category"><%= params[:category] %></h1>

<% if @plays.count == 0 %>
<h3>There are no plays in this category</h3>
<% else %>
<div class="row">
  <% @plays.each do |play| %>
  <div class="col-md-3">
    <a href="/plays/<%= play.id %>">
      <%= image_tag play.play_img.url(:play_index), class: "play" %>
    </a>
  </div>
  <% end %>
</div>
<% end %>

app/views/plays/new.html.erb
<h1>New Play</h1>

<%= render "form" %>

app/views/plays/show.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="row">
    <div class="col-md-4">
      <%= image_tag @play.play_img.url(:play_show), id: "play-show" %>
    </div>

    <div class="col-md-8">
      <div id="play-info"></div>
      <h1><%= @play.title %></h1>
      <h3><span><em>Directed by </em></span><%= @play.director %></h3>
      <h4><%= @play.category.name %></h4>
      <h4>Average Rating</h4>
      <div id="average-review-rating" data-score="<%= @average_review %>"></div><br>
      <span class="number-of-review"><em> From </em><%= @play.reviews.count %> reviews </span>
      <div id="actions">
        <% if user_signed_in? %>
        <% if current_user.id == @play.user_id %>
        <h5><%= link_to "Edit", edit_play_path(@play) %> | <%= link_to "Delete", play_path(@play), method: :delete, data: { confirm: "Are you sure?" } %></h5>
        <% end %>
        <% end %>
      </div>
      <p><%= simple_format(@play.description) %></p>
    </div>

  </div>

  <div class="row">
    <div id="review-info">
      <h1>Reviews</h1>
      <%= render @play.reviews %>
      <%= link_to "Add Review", new_play_review_path(@play), class: "btn btn-primary" %>
    </div>
  </div>
</div>

<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
  $('#average-review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/reviews/_form.html.erb
<%= form_for([@play, @play.reviews.build]) do |f| %>

<div id="rating-form">
  <label>Rating</label>
</div>

<div class="form-group">
  <%= f.label :comment %>
  <%= f.text_area :comment, rows: "2", class: "form-control" %>
</div>

<%= f.submit "Rate!", class: "btn btn-primary" %>

<% end %>

<script>
$('#rating-form').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
});
</script>

app/views/reviews/_review.html.erb
<div id="reviews">
  <h4><%= review.user.email %></h4>
  <div class="review-rating" data-score="<%= review.rating %>"></div></br>
  <p><%= review.comment %></p>
  <% if user_signed_in? %>
    <% if review.user_id == current_user.id %>
      <div id="links">
        <%= link_to "Edit", edit_play_review_path(review.play, review) %> | <%= link_to "Delete", play_review_path(review.play, review), method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-10 col-md-offset-1">
  <div id="edit-review">
    <%= form_for([@play, @review]) do |f| %>

    <div id="rating-form">
      <label for="rating-form"> Rating </label>
    </div>

    <div class="form-group">
      <%= f.label :comment %>
      <%= f.text_area :comment, rows: "2", class: "form-control" %>
    </div>

    <%= f.submit "Update", class: "btn btn-primary" %>

    <% end %>

  </div>
</div>

<script>
$('#rating-form').raty({
  path: '/assets/',
  scoreName: 'review[rating]'
});
</script>

app/views/reviews/new.html.erb
<div class="col-md-10 col-md-offset-1">
  <div>
    <h1>Post Review</h1>
    <%= render 'form' %>
  </div>
</div>